### ISSUE TITLE
Allow token transfer with data from a smart contract to another smart contract

### ISSUE THREAD

**Issue by lcswillems** [ElrondNetwork/wasm-vm#568]
## Problem

It is frequent that a caller A calls a SC B with a token, the SC B transforms the received token and then send the transformed token back to the caller A.

In the case where the caller A is a SC and the SC B sends back the token with additional data (e.g. `self.send().direct(&receiver, &id, &nonce, &amount, b"Some data")`), the transaction will fail with the error `Not enough gas`. You can see a reproduction of the issue [here](https://github.com/jacobleygonie/Elrond-token-transfer-bug).

We believe that from a developer point of view (if we forget the blockchain implementation details that leads to this error), the transaction should not fail. The additional data should be written in the blockchain and the token should be transferred, but no smart contract call should be done.

Currently, the transaction fails because `self.send().direct(..., b"Some data")` sends a token to the receiver while setting the gasLimit to 0 and the function name to "Some data". In other words, the blockchain will not only send the token to the receiver but all call the method "Some data" of the receiver. However, because the gasLimit is set to 0, the transaction will necesseraly fail.

## Solution

We believe the blockchain should try to call the receiver method only if the receiver is a smart contract, a function name has been specified, and **gasLimit > 0**.

We made a pull request to fix this: https://github.com/ElrondNetwork/wasm-vm/pull/569

**Comment by sasurobert** [comment]
self.send.direct will be changed on rust framework to not allow data. This is a much more consistent way to do it.
